version: 0.2

phases:

  pre_build:
    commands:
      ## CONFIGURE THIS: Repo name, please make sure this repo exists in ECR
      - export IMAGE_REPO_NAME=ecs-encryption-blog-proxy

  build:
    commands:
      ## Build docker image
      - echo Building the Docker image...

      ## Automate version tagging based on datetime for now, ideally should be tied to release tags
      - export LATEST_TAG=latest

      # Get AWS Account Id
      - export AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -d':' -f 5)

      # Build docker image
      - docker build -t $IMAGE_REPO_NAME:$LATEST_TAG -f Dockerfile-proxy .
      - docker tag $IMAGE_REPO_NAME:$LATEST_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$LATEST_TAG

  post_build:
    commands:
      # Login to to ECR, this means code build has this role
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      
      # Push Docker Image
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$LATEST_TAG

artifacts:
  files:
    - '**/*'
  base-directory: buildoutput