FROM envoyproxy/envoy-alpine-dev:latest

ENV TZ=America/New_York \
    DEBIAN_FRONTEND=noninteractive

RUN apk update && apk add python3 bash curl; pip3 install -q Flask==0.11.1 requests==2.18.4; mkdir /code

ADD ./service.py /code

EXPOSE 8080

CMD ["python3", "/code/service.py"]
